### ISSUE TITLE
extending components?

### ISSUE THREAD

**Issue by arohner** [dvingo/cljs-styled-components#5]
```
(defstyled button :button {:type "button"
                           :dummy (fn [props]
                                    (js/console.log "props:" props)
                                    (println "clj props:" ((clj-props identity) props)))})

(defstyled styled-button button {:styled/mixins [space color]})

(defstyled primary styled-button {:color "blues.1"
                                  :bg "colors.white"})

(r/as-element [primary {} "Primary"])
```

This does not work, and I'm not sure why. As I understand it, the CLJS map in `primary` should get passed through to styled-button and button, but they are not. 

```
(r/as-element [primary {:bg "blues.1"} "Primary"])
```
renders as expected, but I'd like to encapsulate that in the `defstyled` definition.

**Comment by dvingo** [comment]
The root cause of the problem was that the cljs wrapper wasn't designed with this use case in mind. When trying out your example the styles get inserted as static strings instead of being invoked by the `color` mixin:
![styles](https://user-images.githubusercontent.com/467827/66726026-ce4ddd00-ee04-11e9-8b68-3778e949679b.png)

This is an implementation detail of this library, but the fundamental abstraction this library provides is invoking the `styled` function as a template string. This means when you pass your styles to `primary` above the object is treated as a collection of css properties, not as a JS object to be handled by styled-components dynamically.
Looking at the styled-components documentation again, I see you can alternatively pass an object (or a function): https://www.styled-components.com/docs/advanced#style-objects instead of using the template string. I think this approach would result in support for the functionality you're seeking. That will require a larger re-write of this library, which I may look into.
In the meantime you can get the functionality you're trying to achieve by using a regular function instead:
```clojure
(defn primary-btn2
  ([] (primary-btn {"color" "blues.1" "bg" "colors.white"}))
  ([props]
   (if (string? props)
     (primary-btn {"color" "blues.1" "bg" "colors.white"} props)
     (primary-btn (clj->js (merge {"color" "blues.1" "bg" "colors.white"} (js->clj props))))))
  ([props & children]
    (primary-btn (clj->js
                   (merge {"color" "blues.1" "bg" "colors.white"} (js->clj props))) children)))
```
This is a bit convoluted in order to deal with all the combinations of props/children you can pass to a component, but shows the general pattern which is to encapsulate the props you want to be bound in this function helper. (this is just sample code, any of the usual ways to write react components will suffice as well).

Apologies if this isn't clear, let me know if you have any questions.

**Comment by dvingo** [comment]
In looking into this a little further, the properties you have being passed to "primary":
```clojure
(defstyled primary styled-button {:color "blues.1"
                                  :bg "colors.white"})
```
Would not work in JS styled components either:

```js
const button = styled("button")({
  type: "button",
  dummy: props => (/* ... */)
})
const styledButton = styled(button)(space, color)
const primary = styled(styledButton)({
  color: "blues.1",
  bg: "colors.white" // <-- gets inserted into a stylesheet in the browser with these values.
})

React.createElement(primary, {})
```
The styled-system library intends for those props to be passed to the final rendered component, the keys passed to styled invocations should be valid css properties.

styled-system is just using theme support of styled-components, so to get the functionality
you wanted above would look like:

```clojure
(defstyled primary styled-button 
  {:color 
    #(goog.object/getValueByKeys % "theme" "colors" "blues" "1")
   :background
  ;; you could bring in a lib that makes this access nicer of course
  ;; #(oget % "theme.colors.white")
    #(goog.object/getValueByKeys % "theme" "colors" "white")})

(r/as-element [primary {} "Primary"])
```
Where your theme would look something like:
```clojure
 #js {:theme #js {:colors #js {:blues #js {"1" "rgb(0,90,200)"} :white "#fff"}}}
```

The way I understand styled-system is that the shorthand properties it provides are intended to be passed as props to components within a render function of a react component, not to be used within style definitions.
